# Generated by Django 5.0.6 on 2024-06-09 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clique_of_the_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneur_of_the_Year_Female',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneur_of_the_Year_Male',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Most_Fashionable_Female',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Most_Fashionable_Male',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Most_Influential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Most_Popular_Female',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Most_Popular_Male',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Most_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Media_Content_Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sportsman_of_the_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sportswoman_of_the_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clique_of_the_Year_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_for_Clique_of_the_Year', to='nuapp.clique_of_the_year')),
                ('Entrepreneur_of_the_Year_Female_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entrepreneur_of_the_Year_Female', to='nuapp.entrepreneur_of_the_year_female')),
                ('Entrepreneur_of_the_Year_Male_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_for_public_relations_officer', to='nuapp.entrepreneur_of_the_year_male')),
                ('Most_Fashionable_Female_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Most_Fashionable_Female', to='nuapp.most_fashionable_female')),
                ('Most_Fashionable_Male_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_for_Most_Fashionable_Male', to='nuapp.most_fashionable_male')),
                ('Most_Influential_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Most_Influential', to='nuapp.most_influential')),
                ('Most_Popular_Female_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_for_Most_Popular_Female', to='nuapp.most_popular_female')),
                ('Most_Popular_Male_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_for_Most_Popular_Male', to='nuapp.most_popular_male')),
                ('Most_Social_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_for_Most_Social', to='nuapp.most_social')),
                ('Social_Media_Content_Creator_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Social_Media_Content_Creator', to='nuapp.social_media_content_creator')),
                ('Sportsman_of_the_Year_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_for_Sportsman_of_the_Year', to='nuapp.sportsman_of_the_year')),
                ('Sportswoman_of_the_Year_voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_for_Sportswoman_of_the_Year', to='nuapp.sportswoman_of_the_year')),
            ],
        ),
        migrations.DeleteModel(
            name='assistant_general_secretary',
        ),
        migrations.DeleteModel(
            name='assistant_social_director',
        ),
        migrations.DeleteModel(
            name='Financial_Secretary',
        ),
        migrations.DeleteModel(
            name='General_Secretary',
        ),
        migrations.DeleteModel(
            name='P_R_O1',
        ),
        migrations.DeleteModel(
            name='P_R_O2',
        ),
        migrations.DeleteModel(
            name='President',
        ),
        migrations.DeleteModel(
            name='Public_Relations_Officer',
        ),
        migrations.DeleteModel(
            name='Social_Director',
        ),
        migrations.DeleteModel(
            name='Sports_Director',
        ),
        migrations.DeleteModel(
            name='Technical_Director',
        ),
        migrations.DeleteModel(
            name='Treasurer',
        ),
        migrations.DeleteModel(
            name='Vice_President',
        ),
        migrations.DeleteModel(
            name='Welfare_Director',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='matric_number',
            new_name='name',
        ),
        migrations.AddField(
            model_name='uservote',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nuapp.userprofile'),
        ),
    ]
